apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world-job
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  template:
    spec:
      containers:
        - name: hello-world-container
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Hello, World!"
              echo "Sleeping for {{ .Values.job.sleepSeconds }} seconds..."
              sleep {{ .Values.job.sleepSeconds }}
              echo "Exiting with code {{ .Values.job.exitCode }}"
              exit {{ .Values.job.exitCode }}
      restartPolicy: Never
